### ISSUE TITLE
Fuzzy search doesn't seem to be working

### ISSUE THREAD

**Issue by piotryordanov** [nyarly/rofi-taskwarrior#5]
Title says it all.
Even tho the README says that fuzzy search should be working!

**Comment by nyarly** [comment]
I'm a little bit confused by your issue here - the fuzzy search behavior is provided by Rofi, and works well for me. Granted, it's a surprisingly subtle UI behavior, so it may not be working as you expect.

What, specifically, isn't working as you expect?

**Comment by piotryordanov** [comment]
My bad, this has to do with rofi.
I had to enable these 3 settings for it to work in an fzf fuzzy search:

```
configuration {
    sort:                true;
    matching:            "fuzzy";
    sort-method:         "fzf";
}
```
